<?php

	//DEFINE ALL THE CONFIGURATION SETTINGS
	DEFINE('HOST', 'localhost');
	DEFINE('USERNAME', '');
	DEFINE('PASSWORD','');
	DEFINE('DB_NAME','');
	DEFINE('EMAIL', '');
	DEFINE('APP_URL', 'https://friendscores.com');
	DEFINE('MIN_QUESTION_ID','24');
	DEFINE('MAX_QUESTION_ID','55');
	DEFINE('NUMBER_OF_QUESTIONS_TO_ASK',15);

?>